# Generated by Django 3.2 on 2022-08-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220808_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origina_cart',
            new_name='original_cart',
        ),
    ]
